# Lug'atlar
[[translations]]
en = "infiltrate"
uz = "kirish"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "debug"
uz = "debag"
part_of_speech = "verb"
description = "Kod yozishda xatolik kelib chiqsa kodni debag qilish kerak boʻladi"
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "debugging"
uz = "debaglash"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "sensor"
uz = "sensor"
part_of_speech = "noun"
description = ""
pronunciation_uz = "sensr"
similar = [""]
status = "Pending review"

[[translations]]
en = "multithread"
uz = "koʻp oqimli"
part_of_speech = "adjective"
description = "Ko'p oqimli ishlov berish jarayoni haqida atama."
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "single thread"
uz = "bir oqimli"
part_of_speech = "adjective"
description = "Bitta oqim bilan ishlaydigan jarayon."
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "concurrency"
uz = "parallel ishlash"
part_of_speech = "noun"
description = "Bir nechta vazifalarni bir vaqtda boshqarish."
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "parse"
uz = "pars"
part_of_speech = "verb"
description = ""
pronunciation_uz = "pars"
similar = [""]
status = "Pending review"

[[translations]]
en = "parsing"
uz = "parsing"
part_of_speech = "noun"
description = ""
pronunciation_uz = "parsing"
similar = [""]
status = "Pending review"

[[translations]]
en = "IT"
uz = "AT"
part_of_speech = "noun"
description = "Axborot texnologiyalar"
pronunciation_uz = "ayti"
similar = [""]
status = "Pending review"

[[translations]]
en = "authentication"
uz = "tasdiqlash"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "authorization"
uz = "ruxsat"
part_of_speech = "noun"
description = "tasdiqlash deb tarjima chiqyapti lekin ruxsat ma'nosida keldi ko'pincha meni tajribamda"
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "option"
uz = "tanlov"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "framework"
uz = "freymvork"
part_of_speech = "noun"
description = ""
pronunciation_uz = "Freymvo'rk"
similar = [""]
status = "Pending review"

[[translations]]
en = "folder"
uz = "jild"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "directory"
uz = "katalog"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "branch"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "account"
uz = "hisob"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "username"
uz = "foydalanuvchi nomi"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "advanced"
uz = ""
part_of_speech = "adjective"
description = "qiyinchilik darajasi"
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "layout"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "release"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "category"
uz = "turkum"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "original"
uz = "asl nusxa"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "fuzzy"
uz = ""
part_of_speech = "adjective"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "progress"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "error"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "reviewer"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "review"
uz = ""
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "workflow"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "scrape"
uz = ""
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "repository"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "feedback"
uz = "sharh"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "firmware"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "charge"
uz = "quvvatlash"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = ["zaryadlash"]
status = "Pending review"

[[translations]]
en = "citizen"
uz = "vatandosh"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = ["fuqaro"]
status = "Pending review"

[[translations]]
en = "two-step verification"
uz = "ikki bosqichli tasdiqlash"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "copy"
uz = "nusxa olish"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = ["nusxalash"]
status = "Pending review"

[[translations]]
en = "favorites"
uz = "saralanganlar"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "e-mail"
uz = "e-pochta"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "mail"
uz = "pochta"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "suspend"
uz = "uyqu holati"
part_of_speech = "verb"
description = "kopyuterni dipleyini o'chitib qo'yish lekin quvvatdan uzilmagan holda"
pronunciation_uz = ""
similar = ["sleep"]
status = "Pending review"

[[translations]]
en = "motherboard"
uz = "ona plata"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = ["bosh plata", "bosh qismi iya"]
status = "Pending review"

[[translations]]
en = "emoji"
uz = "hisbelgi"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "accent color"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Needs translation"

[[translations]]
en = "FAQ"
uz = "KBS"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Needs translation"

[[translations]]
en = "pipeline"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Needs translation"

[[translations]]
en = "preview"
uz = "razm solish"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "preview"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Needs translation"

[[translations]]
en = "media"
uz = "multimedia"
part_of_speech = ""
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "mention"
uz = "zikrlamoq"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "encrypt"
uz = "shifrlash"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "decrypt"
uz = "deshifrlash"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "encode"
uz = "kodlash"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "decode"
uz = "dekodlash"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "theme"
uz = "mavzu"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "distribution"
uz = "distributiv"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Approved"

[[translations]]
en = "counter"
uz = "hisoblagich"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "release"
uz = "reliz"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "command line interface"
uz = "buyruq satri interfeysi"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "artificial intelligence"
uz = "sunʼiy intellekt"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "AI"
uz = "SI"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "toggle"
uz = "oʻzgartirish"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "monospace"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Needs translation"

[[translations]]
en = "collapse"
uz = "yigʻish"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "expand"
uz = "yoymoq"
part_of_speech = "verb"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "pattern"
uz = ""
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

[[translations]]
en = "AM"
uz = "TO"
part_of_speech = "noun"
description = "Tushdan oldin"
pronunciation_uz = ""
similar = [""]
status = "Approved"

[[translations]]
en = "PM"
uz = "TK"
part_of_speech = "noun"
description = "Tushdan keyin"
pronunciation_uz = ""
similar = [""]
status = "Approved"

[[translations]]
en = "OS"
uz = "OT"
part_of_speech = "noun"
description = "Operatsion tizim"
pronunciation_uz = ""
similar = [""]
status = "Approved"

[[translations]]
en = "pattern"
uz = "qobiq"
part_of_speech = "noun"
description = ""
pronunciation_uz = ""
similar = [""]
status = "Pending review"

# Template for new words
# [[translations]]
# en = ""
# uz = ""
# part_of_speech = ""
# description = ""
# pronunciation_uz = ""
# similar = [""]
# status = "Needs translation"
