# Configuration for GitHub's Issue Template chooser

# -------------------------------------------------------------------------
# English Templates
# -------------------------------------------------------------------------
blank_issues_enabled: false
contact_links:
  # - name: Ask a question about localization data
  #   url: https://github.com/uzbek-net/dictionary/discussions
  #   about: Please ask and answer questions here. (Optional link to discussions)

# -------------------------------------------------------------------------
# Template Links
# -------------------------------------------------------------------------
issue_templates:
  # --------------------
  # Translation Issues
  # --------------------
  # - name: ðŸš¨ Incorrect Translation Report (English)
  #   description: Report a translation that is wrong, inaccurate, or could be improved.
  #   link: INCORRECT_TRANSLATION_REPORT.md

  - name: ðŸš¨ Xato Tarjima Xisoboti (OÊ»zbekcha)
    description: NotoÊ»gÊ»ri, noaniq yoki yaxshilanishi mumkin boÊ»lgan tarjimani xabar qiling.
    link: XATO_TARJIMA_HAQIDA_XABAR_BERISH.md

  # --------------------
  # New Content
  # --------------------
  # - name: âœ¨ New Word Proposal (English)
  #   description: Propose a new English term and its official Uzbek translation for the dictionary.
  #   link: NEW_WORD_PROPOSAL.md

  - name: âœ¨ Yangi So'z Taklifi (O'zbekcha)
    description: LugÊ»atga yangi inglizcha texnik atama va uning rasmiy oÊ»zbekcha tarjimasini taklif qiling.
    link: YANGI_SOÊ»Z_TAKLIF_QILISH.md

  # --------------------
  # Feature/System Improvement
  # --------------------
  # - name: ðŸ’¡ Feature Request / Improvement (English)
  #   description: Suggest an idea, enhancement, or new feature for the dictionary structure or process.
  #   link: FEATURE_REQUEST.md

  - name: ðŸ’¡ Yangi Funksiya Talabi / Yaxshilash (O'zbekcha)
    description: LugÊ»at tizimini yaxshilash uchun gÊ»oya yoki taklif bering.
    link: YANGI_FUNKSIYA_TAKLIFI.md