name: Update uz.po from dictionary.toml

on:
  push:
    branches:
      - main
    paths:
      - dictionary.toml

permissions:
  contents: write

jobs:
  update-uz-po:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run converter.py
        run: python ./scripts/toml2po_converter.py

      - name: Commit and push uz.po
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add locale/uz.po
          git commit -m "Update uz.po from dictionary.toml" || echo "No changes"
          git push